// Cars
export const CARS_SEARCH_REQUEST = 'CARS_SEARCH_REQUEST';
export const CARS_SEARCH_SUCCESS = 'CARS_SEARCH_SUCCESS';
export const CARS_SEARCH_FAILURE = 'CARS_SEARCH_FAILURE';

// Searh Form
export const SEARCH_FORM_SET_DEST = 'SEARCH_FORM_SET_DEST';
export const SEARCH_FORM_SET_STARTDATE = 'SEARCH_FORM_SET_STARTDATE';
export const SEARCH_FORM_SET_PICKUPTIME = 'SEARCH_FORM_SET_PICKUPTIME';
export const SEARCH_FORM_SET_ENDDATE = 'SEARCH_FORM_SET_ENDDATE';
export const SEARCH_FORM_SET_DROPOFFTIME = 'SEARCH_FORM_SET_DROPOFFTIME';

export const SEARCH_FORM_CLEAR_DEST = 'SEARCH_FORM_CLEAR_DEST';
export const SEARCH_FORM_CLEAR_STARTDATE = 'SEARCH_FORM_CLEAR_STARTDATE';
export const SEARCH_FORM_CLEAR_PICKUPTIME = 'SEARCH_FORM_CLEAR_PICKUPTIME';
export const SEARCH_FORM_CLEAR_ENDDATE = 'SEARCH_FORM_CLEAR_ENDDATE';
export const SEARCH_FORM_CLEAR_DROPOFFTIME = 'SEARCH_FORM_CLEAR_DROPOFFTIME';
