// Cars
export const CARS_SEARCH_REQUEST = 'CARS_SEARCH_REQUEST';
export const CARS_SEARCH_SUCCESS = 'CARS_SEARCH_SUCCESS';
export const CARS_SEARCH_FAILURE = 'CARS_SEARCH_FAILURE';

// Searh Form
export const SEARCH_FORM_SET_DEST = 'SEARCH_FORM_SET_DEST';
export const SEARCH_FORM_SET_STARTDATE = 'SEARCH_FORM_SET_STARTDATE';
export const SEARCH_FORM_SET_PICKUPTIME = 'SEARCH_FORM_SET_PICKUPTIME';
export const SEARCH_FORM_SET_ENDDATE = 'SEARCH_FORM_SET_ENDDATE';
export const SEARCH_FORM_SET_DROPOFFTIME = 'SEARCH_FORM_SET_DROPOFFTIME';

export const SEARCH_FORM_CLEAR_DEST = 'SEARCH_FORM_CLEAR_DEST';
export const SEARCH_FORM_CLEAR_STARTDATE = 'SEARCH_FORM_CLEAR_STARTDATE';
export const SEARCH_FORM_CLEAR_PICKUPTIME = 'SEARCH_FORM_CLEAR_PICKUPTIME';
export const SEARCH_FORM_CLEAR_ENDDATE = 'SEARCH_FORM_CLEAR_ENDDATE';
export const SEARCH_FORM_CLEAR_DROPOFFTIME = 'SEARCH_FORM_CLEAR_DROPOFFTIME';


// Places, autocomplete, place details, response data from google API
export const PLACES_AUTOCOMPLETE_REQUEST = 'PLACES_AUTOCOMPLETE_REQUEST';
export const PLACES_AUTOCOMPLETE_SUCCESS = 'PLACES_AUTOCOMPLETE_SUCCESS';
export const PLACES_AUTOCOMPLETE_FAILURE = 'PLACES_AUTOCOMPLETE_FAILURE';

export const PLACES_DETAILS_REQUEST = 'PLACES_DETAILS_REQUEST';
export const PLACES_DETAILS_SUCCESS = 'PLACES_DETAILS_SUCCESS';
export const PLACES_DETAILS_FAILURE = 'PLACES_DETAILS_FAILURE';
